#include<stdio.h>
#include<stdlib.h>
intpos;
structnode{
intdata;
structnode*Llink,*Rlink;
}*head=NULL,*ptr,*ptr1;
intinsert_front()
{
printf("\nInsertionatfront\nEnteryourdata:");
ptr=(structnode*)malloc(sizeof(structnode*));
scanf("%d",&ptr->data);
if(head==NULL)
head=ptr;
else{
head->Llink=ptr;
ptr->Rlink=head;
head=ptr;
}
}
intinsert_end()//ToInsertatEnd
{
printf("\nInsertionatEnd\nEnteryourdata:");
ptr=(structnode*)malloc(2*sizeof(structnode*));
scanf("%d",&ptr->data);
if(head==NULL){
head=ptr;
head->Llink=NULL;
}
else{
ptr1=head;
while(ptr1->Rlink!=NULL)
ptr1=ptr1->Rlink;
ptr1->Rlink=ptr;
ptr->Llink=ptr1;

}
ptr->Rlink=NULL;
}
voidinsert_pos(){
printf("Enterposition:");
scanf("%d",&pos);
ptr=(structnode*)malloc(sizeof(structnode*));
if(ptr==NULL)
printf("OVERFLOW\n");
else{
printf("\nData:");
scanf("%d",&ptr->data);
ptr1=head;
if(pos==1){
ptr->Rlink=ptr1;
ptr->Llink=NULL;
head=ptr;
return;
}
for(inti=1;i<pos-1;i++)
ptr1=ptr1->Rlink;
ptr->Rlink=ptr1->Rlink;
ptr->Llink=ptr1;
ptr1->Rlink=ptr;
}
}
voiddelete_front()
{
if(head==NULL)
printf("EMPTYLIST\n");
else{
ptr=head;
head=ptr->Rlink;
head->Llink=NULL;
free(ptr);
printf("deletedfrom begining..\n");
}
}
voiddelete_end()
{
ptr=head;
if(head==NULL)
printf("EMPTYLIST\n");
elseif(head->Rlink==NULL){
head=NULL;

free(ptr);
printf("onlyonenode..deletedit..\n");
}
else{
structnode*prev;
while(ptr->Rlink!=NULL){
prev=ptr;
ptr=ptr->Rlink;
}
prev->Rlink=NULL;
free(ptr);
printf("Deletedfronend..\n");
}
}
voiddelete_pos()
{
printf("enterpositiontodelete:");
scanf("%d",&pos);
structnode*prev,*temp;
ptr=head;
for(inti=1;i<pos;i++){
if(head==NULL){
printf("Can'tdelete!!Listisempty\n");
return;
}
prev=ptr;
ptr=ptr->Rlink;
}
temp=ptr;
ptr=ptr->Rlink;
prev->Rlink=ptr;
ptr->Llink=prev;
free(temp);
printf("deletedfrom index%d\n",pos-1);
}
voidprint()//ToPrintLinkedListData
{
printf("\nDatainthelinkedlist\n");
ptr=head;
while(ptr!=NULL)
{
printf("%d",ptr->data);
ptr=ptr->Rlink;
}printf("\n");
}
voidmain()

{
intop=1;
printf("\nINSERTION 1:FRONT2:END3:POSITION\nDELETION 4:FRONT5:END
6:POSITION\n7:PRINT8:EXIT\n");
scanf("%d",&op);
while(op)
{
ptr=(structnode*)malloc(20*sizeof(structnode*));
switch(op)
{
case1:insert_front();
break;
case2:insert_end();
break;
case3:insert_pos();
break;
case4:delete_front();
break;
case5:delete_end();
break;
case6:delete_pos();
break;
case7:print();
break;
case8:printf("EXIT\n");
exit(0);
break;
default:printf("InvalidChoice\n");
}
printf("\nINSERTION 1:FRONT2:END3:POSITION\nDELETION 4:FRONT

5:END6:POSITION\n7:PRINT8:EXIT\n");

scanf("%d",&op);
}
}